from pathlib import Path
import argparse
import os
import sys
import open3d as o3d


def extract_obj_material_directives(original_obj_path: str | Path) -> tuple[list[str], list[str]]:
    """
    Extracts material library and material-use directives from the original OBJ.

    Returns:
      mtllib_lines: unique mtllib lines, e.g. ["mtllib mesh.mtl"]
      usemtl_lines: unique usemtl lines, e.g. ["usemtl material_0"]

    For your single-texture workflow, the first usemtl is usually enough.
    """
    original_obj_path = Path(original_obj_path)

    mtllib_lines = []
    usemtl_lines = []

    with original_obj_path.open("r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            stripped = line.strip()

            if stripped.startswith("mtllib "):
                if stripped not in mtllib_lines:
                    mtllib_lines.append(stripped)

            elif stripped.startswith("usemtl "):
                if stripped not in usemtl_lines:
                    usemtl_lines.append(stripped)

    return mtllib_lines, usemtl_lines


def patch_obj_to_reference_original_materials(
    generated_obj_path: str | Path,
    original_obj_path: str | Path,
    fallback_mtl_filename: str = "mesh.mtl",
    fallback_material_name: str = "material_0",
) -> None:
    """
    Modifies the generated OBJ so it references the original MTL/texture setup.

    It does not copy or rewrite the MTL/JPG.
    It only adds:
      mtllib mesh.mtl
      usemtl <material>

    The MTL must remain beside the OBJ, and the MTL should reference texture.jpg.
    """
    generated_obj_path = Path(generated_obj_path)
    original_obj_path = Path(original_obj_path)

    mtllib_lines, usemtl_lines = extract_obj_material_directives(original_obj_path)

    if not mtllib_lines:
        mtllib_lines = [f"mtllib {fallback_mtl_filename}"]

    if not usemtl_lines:
        usemtl_lines = [f"usemtl {fallback_material_name}"]

    generated_lines = generated_obj_path.read_text(
        encoding="utf-8",
        errors="ignore",
    ).splitlines()

    # Remove any material lines generated by Open3D.
    generated_lines = [
        line for line in generated_lines
        if not line.strip().startswith("mtllib ")
        and not line.strip().startswith("usemtl ")
    ]

    patched_lines = []

    # Add original mtllib reference near the top.
    patched_lines.extend(mtllib_lines)

    inserted_usemtl = False

    for line in generated_lines:
        stripped = line.strip()

        # Insert the original material before the first face.
        if stripped.startswith("f ") and not inserted_usemtl:
            # For single-material OBJ workflows, use the first material.
            patched_lines.append(usemtl_lines[0])
            inserted_usemtl = True

        patched_lines.append(line)

    if not inserted_usemtl:
        patched_lines.append(usemtl_lines[0])

    generated_obj_path.write_text(
        "\n".join(patched_lines) + "\n",
        encoding="utf-8",
    )

def ensure_mesh_has_normals_open3d(
    input_mesh_path: str | Path,
    output_mesh_path: str | Path | None = None,
    overwrite: bool = False,
) -> Path:
    """
    Checks whether a mesh has vertex normals.

    If it has normals:
      - returns the original mesh path.

    If it does not:
      - computes vertex normals
      - writes a new mesh file
      - returns the new mesh path.

    Works for mesh formats Open3D can read/write, including .obj, .ply, .stl.
    """
    input_mesh_path = Path(input_mesh_path)

    if output_mesh_path is None:
        output_mesh_path = input_mesh_path.with_name(
            f"{input_mesh_path.stem}_with_normals{input_mesh_path.suffix}"
        )
    else:
        output_mesh_path = Path(output_mesh_path)

    if output_mesh_path.exists() and not overwrite:
        raise FileExistsError(
            f"Output already exists: {output_mesh_path}. "
            "Use overwrite=True to replace it."
        )

    mesh = o3d.io.read_triangle_mesh(str(input_mesh_path))

    if mesh.is_empty():
        raise ValueError(f"Open3D could not read mesh or mesh is empty: {input_mesh_path}")

    if mesh.has_vertex_normals():
        print(f"Mesh already has vertex normals: {input_mesh_path}")
        return input_mesh_path

    print(f"Mesh has no vertex normals. Computing normals: {input_mesh_path}")

    mesh.compute_vertex_normals()
    mesh.normalize_normals()

    ok = o3d.io.write_triangle_mesh(
        str(output_mesh_path),
        mesh,
        write_ascii=True,
        write_vertex_normals=True,
        write_vertex_colors=False,
        write_triangle_uvs=True,
    )

    if not ok:
        raise RuntimeError(f"Failed to write mesh: {output_mesh_path}")
    
    patch_obj_to_reference_original_materials(
        generated_obj_path=output_mesh_path,
        original_obj_path=input_mesh_path,
        fallback_mtl_filename="mesh.mtl",
        fallback_material_name="material_0",
    )

    print(f"Wrote mesh with normals: {output_mesh_path}")
    return output_mesh_path

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create model.sdf and model.config for a Gazebo map folder."
    )

    parser.add_argument(
        "map_folder",
        help="Folder containing mesh.obj, mesh.mtl, and texture.jpg",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing model.sdf and model.config",
    )

    args = parser.parse_args()

    virtr = os.environ.get("VIRTR")
    if not virtr: raise EnvironmentError("VIRTR environment variable is not set. Expected map folders under ${VIRTR}/data/")
    data_dir = Path(virtr).expanduser().resolve() / "data"

    map_dir = data_dir / args.map_folder
    
    try:
        normal_mesh = ensure_mesh_has_normals_open3d(
            map_dir / "mesh.obj",
            map_dir / "mesh_with_normals.obj",
            overwrite=args.overwrite,
        )
        return 0
    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    
if __name__ == "__main__":
    raise SystemExit(main())
    